name: Markdown Lint
on: [pull_request]

jobs:
  lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint-ci
